runtime: python37 # or another supported version

entrypoint: gunicorn --workers 3 --timeout 180 -b :$PORT app:app

instance_class: F2

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

handlers:
# Matches requests to /images/... to files in static/images/...
# - url: /images
#   static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
